### PR TITLE
Jython-windows compat (jython issue 2298): incorrect shebang line

### PR DESCRIPTION
**Pull request by H0**
http://bugs.jython.org/issue2298
This new setuptools actually had some other bugs which are fixed now

### CODE REVIEW

**Comment by jimbaker** [comment]
+1, LGTM. I will see how it works in terms of building the setuptools wheel, and then work on getting this upstreamed into the PyPA official version.

**Comment by jimbaker** [comment]
So we still have a problem in building the necessary exe. Using yolk installation as our test case:

```
running install_scripts
Installing yolk-script.py script to C:\jython2.7rc1-b2\bin
error: C:\jython2.7rc1-b2\Lib\site-packages\setuptools\cli-64.exe: No such file or directory
```

One possible related issue is http://bugs.python.org/setuptools/issue2, which my initial reading suggests that this is part of distutils, possibly just on Windows. I will look into this further.

**Comment by H0** [comment]
It is strange cos i'm on win-64 too, and there is no such error on my side. How do you reproducing that?

**Comment by jimbaker** [comment]
Solved! I simply need to add setuptools/cli-64.exe from Windows CPython to make this work. (jython.exe is built using 64-bit Windows, and as a launcher, it does not need access to the GUI version, or at least that's my assumption.

So I will merge this PR, then add the cli-64.exe separately.

**Comment by jimbaker** [comment]
Here's how to ensure the Windows exe files are included, including cli-64.exe when building the wheel:

```
$ SETUPTOOLS_INSTALL_WINDOWS_SPECIFIC_FILES=1 jpip wheel git+https://github.com/jythontools/setuptools.git
```

I suppose this same wheel could be built on CPython and on Windows to the same effect. We probably should make one more change around this on Jython to assume `SETUPTOOLS_INSTALL_WINDOWS_SPECIFIC_FILES`. In `setup.py` for setuptools, this would mean changing these lines:

```
force_windows_specific_files = (
    os.environ.get("SETUPTOOLS_INSTALL_WINDOWS_SPECIFIC_FILES")
    not in (None, "", "0")
)
if sys.platform == 'win32' or force_windows_specific_files: # ADD for Jython: or os.name == 'java':
    package_data.setdefault('setuptools', []).extend(['*.exe'])
    package_data.setdefault('setuptools.command', []).extend(['*.xml'])
```

**Pull request merged**
